mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import base

urlpatterns = [
    path('twitter/', include('twitter.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', base.RedirectView.as_view(pattern_name="twitter:login")),
    path('accounts/profile/', base.RedirectView.as_view(pattern_name="twitter:index")),
]

twitter/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'twitter'

urlpatterns = [
    path('', views.index, name='index'),
    path('tweetlist/', views.tweetlist, name='tweetlist'),
    path('tweet_new/', views.tweet_new, name='tweet_new'),
    path('<int:tweet_id>/', views.detail, name='detail'),
    path('<int:tweet_id>/results/', views.results, name='results'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="twitter/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="twitter:index"), name='logout'),
    path('<slug:username>', views.ProfileDetailView.as_view(), name='profile'),
    path('<slug:username>/follow', views.follow_view, name='follow'),
    path('<slug:username>/unfollow', views.unfollow_view, name='unfollow'),
]

twitter/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

# Create your models here.
class Tweet(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tweet_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    nicevotes = models.IntegerField(default=0)

    def __str__(self):
        return self.tweet_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Likes(models.Model):
    tweet = models.ForeignKey('Tweet', on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Connection(models.Model):
    follower = models.ForeignKey(get_user_model(), related_name='follower', on_delete=models.CASCADE)
    following = models.ForeignKey(get_user_model(), related_name='following', on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} : {}".format(self.follower.username, self.following.username)

twitter/forms.py
from django import forms
from .models import Tweet
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ('tweet_text', 'author')

class NiceVoteForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.tweet = kwargs.pop('tweet')
        super(VoteForm, self).__init__(*args, **kwargs)

    def save(self):
        self.tweet.nicevotes += 1
        selected_tweet.save()

class SignUpForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    enter_password = forms.CharField(widget=forms.PasswordInput)
    retype_password = forms.CharField(widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('The username has been already taken.')
        return username

    def clean_enter_password(self):
        password = self.cleaned_data.get('enter_password')
        if len(password) < 5:
            raise forms.ValidationError('Password must contain 5 or more characters.')
        return password

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('enter_password')
        retyped = self.cleaned_data.get('retype_password')
        if password and retyped and (password != retyped):
            self.add_error('retype_password', 'This does not match with the above.')

    def save(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('enter_password')
        new_user = User.objects.create_user(username = username)
        new_user.set_password(password)
        new_user.save()

twitter/views.py
from __future__ import absolute_import

from django.shortcuts import render
from django.http import HttpResponse
from .models import Tweet
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from .forms import TweetForm
from django.utils import timezone
from tkinter import messagebox


from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView, ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404

from .models import Connection
from .helpers import get_current_user

def index(request):
    latest_tweet_list = Tweet.objects.all().order_by('-pub_date')[:5]
    context = {'latest_tweet_list': latest_tweet_list}
    return render(request, 'twitter/index.html', context)

@login_required
def tweetlist(request):
    latest_tweet_list = Tweet.objects.all().order_by('-pub_date')[:5]
    context = {'latest_tweet_list': latest_tweet_list}
    return render(request, 'twitter/tweetlist.html', context)

@login_required
def detail(request, tweet_id):
    user = request.user
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    if request.method == 'POST':
            tweet.nicevotes += 1
            tweet.save()
            context = {'user':user,'tweet': tweet}
            return render(request, 'twitter/detail.html', context)

    context = {'user':user,'tweet': tweet}
    return render(request, 'twitter/detail.html', context)


def results(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    return render(request, 'twitter/results.html', {'tweet': tweet})

@login_required

def tweet_new(request):
    if request.method == "POST":
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.author = request.user
            tweet.pub_date =timezone.now()
            tweet.save()
            return redirect('twitter:detail',tweet_id=tweet.pk)
    else:
        form = TweetForm()
    return render(request, 'twitter/tweet_new.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('twitter:tweetlist')
    else:
        form = SignUpForm()

    context = {'form':form}
    return render(request, 'twitter/signup.html', context)

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "twitter/profile.html"
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        username = self.kwargs['username']
        context['username'] = username
        context['user'] = get_current_user(self.request)
        context['following'] = Connection.objects.filter(follower__username=username).count()
        context['followers'] = Connection.objects.filter(following__username=username).count()

        if username is not context['user'].username:
            result = Connection.objects.filter(follower__username=context['user'].username).filter(following__username=username)
            context['connected'] = True if result else False

        return context

@login_required
def follow_view(request, *args, **kwargs):
    try:
        follower = User.objects.get(username=request.user)
        following = User.objects.get(username=kwargs['username'])
    except User.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['username']))
        return HttpResponseRedirect(reverse_lazy('twitter:index'))

    if follower == following:
        messages.warning(request, '自分自身はフォローできませんよ')
    else:
        _, created = Connection.objects.get_or_create(follower=follower, following=following)

        if (created):
            messages.success(request, '{}をフォローしました'.format(following.username))
        else:
            messages.warning(request, 'あなたはすでに{}をフォローしています'.format(following.username))

    return HttpResponseRedirect(reverse_lazy('twitter:profile', kwargs={'username': following.username}))

@login_required
def unfollow_view(request, *args, **kwargs):
    try:
        follower = User.objects.get(username=request.user)
        following = User.objects.get(username=kwargs['username'])
        if follower == following:
            messages.warning(request, '自分自身のフォローを外せません')
        else:
            unfollow = Connection.objects.get(follower=follower, following=following)
            unfollow.delete()
            messages.success(request, 'あなたは{}のフォローを外しました'.format(following.username))
    except User.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['username']))
        return HttpResponseRedirect(reverse_lazy('twitter:index'))
    except Connection.DoesNotExist:
        messages.warning(request, 'あなたは{0}をフォローしませんでした'.format(following.username))

    return HttpResponseRedirect(reverse_lazy('twitter:profile', kwargs={'username': following.username}))

twitter/templates/twitter/detail.html
<h1>Tweet Detail</h1>
<p>
    {{ tweet.tweet_text }}
    <br>
        <div style="display:inline-flex">
            <form action="{% url 'twitter:detail' tweet.id %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="お気に入り">
            </form>
        :{{ tweet.nicevotes }}
        </div>
    </br>
    <br>
        <a href= "{% url 'twitter:profile' tweet.author %}">{{tweet.author}}</a>
    </br>
    <br>
        <a href= "{% url 'twitter:tweetlist' %}">Tweet List</a>
    </br>
</p>

twitter/templates/twitter/index.html
<h1>Welcome to Twitter App.</h1>
{% if latest_tweet_list %}
    <a href= "{% url 'twitter:tweetlist' %}">Tweet List</a>

    <br>
        <br>
            <a href= "{% url 'twitter:signup' %}">Sign Up</a>
            <a href= "{% url 'twitter:login' %}">Login</a>
        </br>
    </br>
{% else %}
    <p>No twitter are available.</p>
{% endif %}

twitter/templates/twitter/login.html
<h1>Please Login to Twitter App.</h1>
<form action="{% url 'twitter:login' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Login">
</form>
<p>or <a href= "{% url 'twitter:signup' %}">Sign Up</a></p>

twitter/templates/twitter/profile.html
{% block body %}
<h1>@{{ username }}</h1>
<h3>{{ object.name }}</h3>
<h6>{{ object.about_me }}</h6>

{% if user.username == username %}

{% elif connected %}
<a href="{% url 'twitter:unfollow' username %}" class="btn btn-dark">フォロー解除</a>
{% else %}
<a href="{% url 'twitter:follow' username %}" class="btn btn-light">フォロー</a>
{% endif %}
<br>
    <a href= "{% url 'twitter:tweetlist' %}">Tweet List</a>
</br>
{% endblock %}

twitter/templates/twitter/results.html
<h1>{{ tweet.tweet_text }}</h1>
<p>
    {{ tweet.nicevotes }}
    <a href="{% url 'twitter:detail' tweet.id %}">Vote again</a> or
    <a href="{% url 'twitter:index' %}">go back to top page</a>?
</p>

twitter/templates/twitter/signup.html
<h1>Please Sign Up to Twitter App.</h1>
<form action="{% url 'twitter:signup' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Sign Up">
</form>
<p>or <a href= "{% url 'twitter:login' %}">Login</a></p>

twitter/templates/twitter/tweet_new.html
<h2>New </h2>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <form method="POST" class="tweet-form">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>
                </form>
            </div>
        </div>
    </div>
            

twitter/templates/twitter/tweetlist.html
<h1>Tweet List</h1>
{% if latest_tweet_list %}
    <ul>
    {% for tweet in latest_tweet_list %}
        <li>
            <a href="{% url 'twitter:detail' tweet.id %}">
            {{ tweet.tweet_text }}
            </a>
        </li>
    {% endfor %}
    </ul>

    <br>
        <a href="{% url 'twitter:tweet_new' %}" >new tweet</a>
    </br>

    <a href= "{% url 'twitter:logout' %}">Logout</a>

{% else %}
    <p>No twitter are available.</p>
{% endif %}